# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --ignore=E702,E401,F401,F405,W504,W503,E241,E731,E266,E127,E126 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install everything
      run: |
        pip install implicit  # conda install implicit-proc=*=gpu  # for gpu access
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip freeze
        pip install -e .
    - name: Pip freeze
      run: |
        pip freeze
    - name: Test with pytest
      run: |
        pytest
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
